### ISSUE TITLE
启动器的下载问题至今未得到解决。

### ISSUE THREAD

**Issue by rechalow** [rechalow/lllauncher#4]
### 复选框

- [X] 我确认我使用的启动器版本是最新的。
- [X] 我确认没有人提出过相同的问题。

### 是否有帮助

对所有人都有帮助

### 简述提出的bug

无论是下载任何东西的时候，均会出现主线程被卡死。初步判定是由于两个或以上同样的Task共享了一个变量，从而导致冲突。

### 重现步骤

点击下载，随便下载一个版本。

### 如何解决

由于TTask并没有Synchonized对线程进行上锁，因此将改用TThread来实现多线程下载。

### 补充

暂无

**Comment by rechalow** [comment]
已修复！下个版本推送！

**Comment by liumingedwin** [comment]
建议 Pull Request. 
显然您似乎不会玩 GitHub.
